import './globals.css';

interface Props {
  children: React.ReactNode
}

export default function RootLayout(props: Props) {

  const { children } = props;

  return (
    <html lang="en">
      <head>
        <title>Next.js 13 Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="bg-slate-100">{children}</body>
    </html>
  );
}
